version: '2'

services: 
    proxy:
        image: orbsnetwork/ethereum-proxy
        ports:
            - 8545:80
        environment: 
            ETHEREUM_ENDPOINT: $ETHEREUM_ENDPOINT
        mem_limit: 256000000

    healthcheck:
        image: orbsnetwork/ethereum-healthcheck
        ports:
            - 8080:8080
        environment:
            ETHEREUM_ENDPOINT: http://proxy/
        mem_limit: 128000000
        links:
            - proxy